sudo: required

services:
    - docker

before_install:
    - docker build -t urbeingwatched8/newproj:sub1 .

script:
    - docker run urbeingwatched8/newproj:sub1 npm test

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push urbeingwatched8/newproj:sub1

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: proj2-sna1234
    env: Proj2Sna1234-env
    bucket_name: elasticbeanstalk-us-east-2-122637044115
    bucket_path: proj2-sna1234
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_acces_key: $AWS_SECRET_KEY
