sudo: required

services:
    - docker

before_install:
    - docker build -t urbeingwatched8/newproj .

script:
    - docker run urbeingwatched8/newproj npm test


deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: proj2-sna444
    env: Proj2Sna444-env
    bucket_name: elasticbeanstalk-us-east-2-122637044115
    bucket_path: proj2-sna444
    on:
        branch: main
    access_key_id: AKIARZDN4ZGJXQZMU7FR
    secret_acces_key: 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
